### ISSUE TITLE
Strange things happen when running GeppettoCoreTests qunit tests on dev branch

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#436]
When running tests before opening any of the samples it seems to hang on ModelFactory with the following error in the log:

```
[2016-06-14 14:09:17.113] ERROR http-bio-8080-exec-3         org.geppetto.frontend.controllers.ConnectionHandler               Error while closing the project org.geppetto.core.common.GeppettoExecutionException: A project without a runtime project cannot be closed
    at org.geppetto.simulation.manager.GeppettoManager.closeProject(GeppettoManager.java:159)
    at org.geppetto.frontend.controllers.ConnectionHandler.closeProject(ConnectionHandler.java:1140)
    at org.geppetto.frontend.controllers.WebsocketConnection.onClose(WebsocketConnection.java:130)
    at org.apache.catalina.websocket.StreamInbound.doOnClose(StreamInbound.java:215)
    at org.apache.catalina.websocket.StreamInbound.closeOutboundConnection(StreamInbound.java:205)
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:136)
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
```

Even when the tests pass - the error above is in the console.

Every now and then the following happens instead (it keeps going forever):
![screenshot 2016-06-14 14 10 06](https://cloud.githubusercontent.com/assets/68134/16044105/f35024e8-323a-11e6-8081-50dac249abae.png)

**Comment by tarelli** [comment]
@gidili they were all passing when I released, see [this](https://github.com/openworm/org.geppetto/issues/498). Clear cache and hard reload?

**Comment by adrianq** [comment]
@gidili @tarelli maybe something to do with not having a user logged-in? This could be the reason why it is not failing if you open a sample project first... I remember to see sth like this a few weeks ago. Not sure though

**Comment by tarelli** [comment]
@adrianq Core tests don't use the persistence bundle

**Comment by gidili** [comment]
@tarelli @adrianq I think I managed to reproduce on live:

1. open GeppettoCoreTests - hangs on ModelFactory (reload a couple of times, still hangs)
2. open HH sample
3. reload GeppettoCoreTests - now it shows that strange error I posted screenshot of with a million "Uncaught type error" (reload a couple of times, still happens)
4. open acnet sample (which is the project tested in GeppettoCoreTests)
5. Reload GeppettoCoreTests - tests now pass consistently (even if I do a clean cache and hard reload)

@tarelli I think you might have opened a bunch of sample when testing the release? That will cause the tests to pass in the steps above.

I remember working on this a few months ago and tests were passing without opening any samples. Weird 😬
